# Generated by Django 2.0.6 on 2019-03-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BootstrapApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUpModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERNAME', models.CharField(default='', max_length=200)),
                ('EMAIL', models.EmailField(default='', max_length=254)),
                ('PASSWORD', models.CharField(default='', max_length=200)),
                ('CONFIRM_PASSWORD', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
